/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    BaseBackstage: typeof import('./src/components/base/BaseBackstage.vue')['default']
    BaseSearch: typeof import('./src/components/base/BaseSearch.vue')['default']
    BaseTable: typeof import('./src/components/base/BaseTable.vue')['default']
    Common: typeof import('./src/components/common/index.vue')['default']
    ContentLayout: typeof import('./src/components/layout/ContentLayout.vue')['default']
    HeaderLayout: typeof import('./src/components/layout/HeaderLayout.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderLayout: typeof import('./src/components/layout/SiderLayout.vue')['default']
  }
}
