/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    2: typeof import('./src/components/layout/HeaderLayout copy 2.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    ADropdownButton: typeof import('ant-design-vue/es')['DropdownButton']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    BackLayout: typeof import('./src/components/layout/BackLayout.vue')['default']
    Base: typeof import('./src/components/base/index.vue')['default']
    BaseBackstage: typeof import('./src/components/base/BaseBackstage.vue')['default']
    BaseBackStage: typeof import('./src/components/base/BaseBackStage.vue')['default']
    BaseBacktage: typeof import('./src/components/base/BaseBacktage.vue')['default']
    BaseSearch: typeof import('./src/components/base/BaseSearch.vue')['default']
    BaseTable: typeof import('./src/components/base/BaseTable.vue')['default']
    Common: typeof import('./src/components/common/index.vue')['default']
    ContentLayout: typeof import('./src/components/layout/ContentLayout.vue')['default']
    copy: typeof import('./src/components/layout/HeaderLayout copy.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HeaderLayout: typeof import('./src/components/layout/HeaderLayout.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderLayout: typeof import('./src/components/layout/SiderLayout.vue')['default']
  }
}
